name: "Dale Manning"
description: "The random thoughts and ideas of a geek..."
permalink: /:categories/:year/:month/:day/:title

url: "http://dalemmanning.me.uk"
feedurl: "feed://dalemmanning.me.uk"

paginate: 10

markdown: rdiscount
permalink: pretty
pygments: true